---
title: data analysis methods for MENA factscheet PH 14.2 - May 2018
author: mz
output: pdf_document
bibliography: "../bib.bib"
---

# Data 

### UN World Population Prospects - [Standard Projections](https://esa.un.org/unpd/wpp/Download/Standard/CSV/)

* **LocID** (numeric): numeric code for the location; for countries and areas, it follows the ISO 3166-1 numeric standard
* **Location** (string): name of the region, subregion, country or area
* **VarID** (numeric): numeric code for the variant
* **Variant** (string): projection variant name (Medium is the most used)
* **Time** (string): label identifying the single year (e.g. 1950) or the period of the data (e.g. 1950-1955)
* **MidPeriod** (numeric): numeric value identifying the mid period of the data, with the decimal representing the month (e.g. 1950.5 for July 1950)
* **AgeGrp** (string): label identifying the single age (e.g. 15) or age group (e.g. 15-19)
* **PopFemale**: Female population for the individual age (thousands)
* **PopTotal**: Total population for the individual age (thousands)
* **PopMale**: Male population for the individual age (thousands)

### UN LifeTables - Mortality Indicators. [*ibid*]

Abridged life tables up to age 85 by sex and both sexes combined providing a set of values showing the mortality experience of a hypothetical group of infants born at the same time and subject throughout their lifetime to the specific mortality rates of a given period, from 1950-1955 to 2095-2100.

* **mx**: Central death rate, nmx, for the age interval (x, x+n)
* **qx**: Probability of dying (nqx), for an individual between age x and x+n
* **px**: Probability of surviving, (npx), for an individual of age x to age x+n
* **lx**: Number of survivors, (lx), at age (x) for 100000 births
* **dx**: Number of deaths, (ndx), between ages x and x+n
* **Lx**: Number of person-years lived, (nLx), between ages x and x+n
* **Sx**: Survival ratio (nSx) corresponding to proportion of the life table population in age group (x, x+n) who are alive n year later
* **Tx**: Person-years lived, (Tx), above age x
* **ex**: Expectation of life (ex) at age x, i.e., average number of years lived subsequent to age x by those reaching age x
* **ax**: Average number of years lived (nax) between ages x and x+n by those dying in the interval

# Calculations

Calculating the *old-age threshold*, which is the age at which the remaining life expectancy is 15 years, was based on the abridged life tables which has **ex** values for five year groups, so I used splines to interpolate the age where **ex** equals 15. 

Although even a linear interpolation would not change the calculations dramatically, so this is a minor point, but still..

I use the `R` `stats` function `splinefun()` and the monotone Hermite spline cumputation according to the method of Fritsch and Carlson: `method = "monoH.FC"` which produces identical results (to the second decimal point)  as the ones published in the IIASA Ageing Demographic Data Sheet [@scherbov2018aging], for a random selection of a dozen country/year combinations. 

See @sanderson2008rethinking for more info on prospective measures of ageing. 



# References