---
title: data analysis journal for MENA factscheet PH 14.2 - May 2018
author: mz
output: pdf_document
bibliography: "../bib.bib"
---

# Wednesday 30.5.

1. New github repository and R project: PH14.02.Factsheets

2. Inspiration: IIASA Ageing Demographic Data Sheet - but turns out not really, althought it's really cool what they do with prospective age and stuff, it's not sth that is easy to run I think, since it requires annual data, which I don't have. 

3. Oh, no, actually it looks like it is available: [Population interpolated by single age, annually from 1950 to 2100.](https://esa.un.org/unpd/wpp/Download/Standard/CSV/), downloaded into `data/raw`, we'll see how interested anyone is in that!

4. OK, copy makefile from last one and copy out all the bespoke stuff. 

5. `make dot`, `make journal`, `make readme` all work. 

6. readme was giving a warning that it requires a nonempty title or pagetitle, so i added a yaml, even though i didn't used to have one. I mean it worked either way, but now there's no warning. 

7. OK, program for data download so it only happens once. 


# Thursday 1.6.

1. OK, so download script is in separate file, so won't need to be run again, then touched the .csv file, so the order is now correct. If I end up downloading any more stuff, just touch it and it will be newer than the prerequisite `00-download`. 

2. I need list of countries in .csv format, manually `cntry.list.csv` in `/raw`,

3. `01-import.R` script to import full WPP population total dataset, extract the countries and save to rds. as processed. 


# Monday 4.6. 

1. After  consulting with Hafiz to exclude mauritania and western sahara and keep turkey. which is nice, since that leaves 20 countries, which should be easy to lay out. Removed the two countries from the country list. 

# Tuesday 5.6.

1. New code script `02-transform-data.R` To set up the data for plotting. 

2. Ach, the dowload scripts are super problematic if they download more than a single file - then if you update the script it always has to redownload all of them. So instead let's put the downloads into the makefile directly as unix commands. 

3. Here's one suggested [solution with curl](https://stackoverflow.com/questions/32672222/how-to-download-a-file-only-if-more-recently-changed-in-makefile) instead of wget. 

4. Well, wget doesn't work on this windows machine anyway, so let's try curl then. And no need to complicate my life with the temp files. Hmm, but it doesn't work with just the file as a target and the curl command as a rule, says "no rule"?! 

5. My bad, there was no rule, because i didn't add the folder. 

6. OK: this is how it works: `curl -o new.filename http://xxx.com` as a rule, 

7. Mini sidetrack trying out multiple cursors in rstudio. nice trick. Although a small bug, since multiline lines are not treated as single lines, which you might presumably expect, no?

8. OK, now the question is how to figure out the old-age threshold, since the life tables data is for 5-year groups. So I need a funciton to get the intercept and slope from two points and then get me the age at which ex is 15. Maybe not linear interpolation either, how about splines? Let's see.

9. Fuck Yes. Splines first attempt with fmm is correct to second decimal compared to the Ageing datasheet from IIASA. 

10. Althought that's actually suspicious. What if they didn't actually make an error? because I am now using the start of the age group, not the middle of the group. So the life expectancy of the group e.g. 50-54 is plotted as the expectancy of 50 year-olds, which is actually wrong, it should be the middle of the group? Actually no, checked in the Andy Hinde book, it is correct . I'll double check a few other country/year combos?

11. Manually checking a few countries to see which method of spline to use. China and Togo 45-50 fit with MonoH.FC method, so does Algeria and Israel, so I'm happy using this. 

# Wednesday 6.6. 

1. OK, keep makefile up to date. `01-import` is now importing and reducing two .csv files, produces two rds files (one is connected via simple dependency only) and these are now inputs to `02-transform-data.R`. 

2. OK, so now in data clean we need to write a function to get the old age threshold for each country/year/gender combo. Also write it up in teh methods.

3. How do you do bibtex in knitted docs again? Ah, OK, that's easy.

4. OK, now write a function to interpolate a single value, using splines, from vectors x and y. And make a very nice roxy example, this in itself could be a blog post about how splines work!

5. Add `FunSPline.R` to makefile. 

6. Clean data for old age threshold plots. 

7. Write draft fundtion for plotting old age thresholds. One for each country, the other 20 totals in the background, and male and female added on top. 

8. Find proportion of population over 65, then proportion over threshold! OK, so this is the population files, and here the issue is that up to a point there was an open ended group fot "80+" peeps. Which is not a number. 

9. OK, now in order to get the proportionof the population over the old age threshold I first need the thresholds for each year. Done

10. Now I need to get the population over that age in each Location/year combination. Got it, that's now an extra row in the population table. 

11. Next step is splitting the year into two rows properly - atm the interpolated population is in the table twice, once as the proportion, and once as part of teh whole population for that age. 

# Thursday 7.6. 

1. OOps, go back one step. The old-age thrshold was calculated for teh abridged life table, so every 5 years, let's fill in the intervening years as well. That makes teh chart smoother.

2. Now restart the population interpolation. I've got it all in one table now, and interpolated

3. Now need to split the full year into the interpolated and difference: If the threshold is 57.3, and there were 30,000 people in the 57 age group, there are now x in the 57.3 age group and 30,000-x in the 57 age group. So some sort of lag function to work only on these two rows. 

4. OK, so I figured that, but there is an issue..Once I plot the proportion over/under the threshold, the fact that I had interpolated to get the five year individual year data is now super obvious and all jumpy.. So I think I may have to go back to five year data here. Oh, or isntead of interpolating the populations, I should only interpolate the proportions, i.e. at the last step. So I've written this all out now on the train, gotta write it up into the methods now..

# Friday 8.6. 

1. OK, so methods, write up with equations the whole process...

2. No, still trying to figure out the jumps. They aren't from the 5 year interpolations actually. They happen everytime the threshold value goes up a notch. So the issue is with the proportional populations above and below the threshold. OK, all good! I shouldn't have interpolated the proportion of the populaiton at the threshold age, ha! My mistake, instead of taking the proportion between two ages, I interpolated the population at that age, which is wrong, since the population is the area, not the height. 

3. This is now fixed, so the population over the old-age threshold is now calculating by assuming the population is uniformly distributed between ages x and x-1. BUT if I want to use splines, then I think I need to do this instead: take the cummulative sum of the population and interpolate that. Presumably the difference will be minimal, but still. 

# Monday 11.6.2018

1. Wrote up methods for calculation of age-old threshold. Including notation, kind of. 

2. Added charts to make clear how the interpolations happen.

3. Read up on numerical analysis to understand what splines are and how they work. 

4. Wrote up interpolation of single years out of five year thresholds. 

5. Also figured out that instead of the linear interpolation of the population over the threshold, I could also use splines if I used the cumulative population size instead. ** But now it's jaggedy again!?


# Tuesday 12.6. 2018

1. Metdhods now written up for interpolation and splines with charts and notation.

2. `02-transform-data.R` is also now updated and working great

3. Smooth pipeline from 02 -> 03 and update makefile. 

4. Move threshold plotting function to own file and make it produce .eps directly. (Add 65 year hline). 

# Wednesday 13.6.2018

1. Separate plotting function from write to postscript.

2. Nah, even better, add `write=TRUE` option to plotting function to pick whether to write to default device or postscript. 

# Thursday 13.6.2018

1. Function for plotting proportions over 65 and over threshold. What should we underlay? 

2. Shit, the interpolation of the cumulative populaiton is actually not working. I never plotted it I guess. The linear interpolatin worked fine, but now it's back to being jaggedy, god knows why. Oh, OK, seems I used < threshold instead of <= threshold. Seems fine now.

3. OK, so plots of old age thresholds and proportion over 65/threshold are done. What else do I need? Pyramids? 

4. Does this mean rewriting my pop pyramid funciton? Now to allow overlaying two pyramids?


# Monday 18.6.2018

1. I'll want to overlay two pyramids, but needs to be the outline of the second one, not filled out. So I need to rewrite the current `rect` code into a `polygon` one. Or rather `lines`. OK, that's now done

# Monday 9.7.2018


1. Do I add the thresholds to the pyramids? there are two thresholds per pyramid, so that could get unwieldy? And the 65 is obviously the same on both. 

2. ALso, it seems all the pyramids are by number not proportion. which should I do in order to overlay them? I think that doesn't matter. but if they are in proportions then at elast they are comarable across the 20 countries. 
So need to go back to the data transforming script and add some props to the pop data. Oh, that was already in the plotting code.. I'll put it in the transforming code thogh, that's where it belongs. 

# Tuesday 10.7.2018

1. OK, now let's add the thresholds to the pyramid plot. I need the data, which is in another dataframe, and I also need the pop size at that year bin to know how long the line should be. Oh, and this has to be different for men and for women obvs. Done

2. And the data should be extracted in the plot funciton based only on the country name. Done

3. can dplyr extract two elements from a pipe? 

4. should all the xlim be the same, no? let's try them. maxi is over 3 though. bot only for men. Let's make it asymetric. Done

5. And add gridlines and 65 age line in background Done

6. let's also add a x=0 line

# Wednesday 11.7.2018

1. Add x axis

2. Aling country name left

3. add save to .eps code to funciton 

4. WOrk on layout of all 3 charts

5. add estimate/projection text to line charts

6. Now figure out background colors, add it as an argument to all the funcitons. 

# Thursday 12.7.2018

1. ugh, getting stuck in the pstricks \def and caluclation stuff. WHy does this not work:

```
\def\x{29.4 4 div}
\psgrid[ \x cm, 1 cm]
```
There is something about defining x as a calculation that fucks it up. 

# Thursday 26.7.2018

1. OK, so the tex file has some sort of issue, it's not compiling. Also, I need to align the grid nicely.

2. Step by step detective work eliminates all causes but for the two Algeria charts. 

3. So what;s wrong with Algeria? Not sure, but rerunning the plots seems OK now. 

4. Tweaks: emphasis in psfrag, main title location in charts.

5. Tweak size so there is more room around each country. 

# Friday 27.7.2018

1. OK, might i do two maps? first need to migrate the map from one of the papers into this project. 

2. OK, two maps provisionally OK. 

# Monday 30.7.2018

1. Add country name labels to map. 

2. So annoying! How to deal with psfrag broken labels. Need to be manually fixed

3. Change layout to 5x6 and adjust plot heights and widths appropriately. 

4. OK, adjust colours

5. Make map scale/legends

6. remove spaces from eps filenames, since includegraphics cannot handle them. 

7. Complete layout

# Tuesday 31.7.2018

1. Write text

# Wednesday 1.8.2018

1. Write text some more.

2. fix line types for m/f

3. keep getting this ghostscript error where the df doesn't compile with a fatal error - and it's tricky to notice, because texmaker just leaves teh previous pdf open. It has sth to do with the .eps files i think, now i'm going one by one to figure out where the culprit is. ALgeria-proportion was the issue. No idea why it was corrupted, just reran it again and it's fine now. 

4. Tunisia also has a psfrag label problem. fixed manually.

5. COuld actually shift all countries by one, because references should fit into one block. UNless I add more footnotes there. Oh, and `\bibhang` is the lenght to adjust to get rid of the indentation in the references. 

6. OK, now create a legend...

7. Add curly braces to ledge. 

8. Pyramid legend almost done.


# Thursday 2.8.2018

1. Make sure all backgrounds are the same (NA)

2. Move the location variable recoding into 02-transform-data.R

3. See what happens with a ps background

4. SHould the map aslo be NA coloured for non mena countries?

5. Ok, play around with colours a bit, almost there

6. The location variable recoding fucks so many things up, i need to take it out again. Now remove it from 02-transform and fix all the stuff that got muddled up...

7. Location is now left as is, because the mapping join depends on it. Instead i just use the plotting fucntions to just take the first 4 letters or sth?


# Friday 3.8.2018

1. Finish the pyramid legend, maybe with background?

2. Proportion legend is missing lines..

3. OK, add pyramid labels. Maybe a proper legend for the two actual pyramids? OK, legends seem fine.

4. I think the country names could be a bit higher

5. Bits and bobs, looking good. 

# Wednesday 8.8.18

1. OK, let's first update the makefile and make sure it works properly as a whole. WHy did I stop doing this as i went along?!
* `journal` = OK
* `readme` = OK, add make.png and a bit more info
* `dot` = OK
* `01-import` = OK
* `02-transform-data` - looks like I deleted the demo stuff! that goes into the mehtods report, so found that again and added it.
* `methods` = OK, add `bib.bib`
* change assignments to `:=` (simple assignment, immediately expanded) just because it was inconsistent
* `03-plotting` = OK
* `04-mapping`: hm, there is some data import and cleaning going on there that needs to be taken out now.. 
* careful, in 01 there is also a country list that was not reproducably sourced.. So I've added it directly and removed that .cvs to make it reproducable.  
* running whole latex thing didn't work because of relative paths to figures in .tex file. try `\graphicspath` to set several options in the preamble. 
* fixed the .bib file relativity as well and now it seems to work! (see tiddlywiki)
* still issue with running a bunch of stuff that neednt be run? Sorted 
* First split the .eps files so they are not overlapping. OK
* Hm, so what to do when i want to use the same parameter e.g. a colour in two `.R` files? TODO
* Also, because the latex and dvips stuff is so verbose, i can't see the --degug information..
* Make sure all relative path references use `here::here()` to be safe! OK

2. Looks like this is all done!
3. Except still have the issue of multiple outputs (esp figures) from a single R script and how to handle that in Make
